module.exports = {
  server_error: "Internal server error",

  token_invalid: "Invalid token",
  followId_invalid: "Invalid followerId",
  auction_invalid: "Invalid auction",
  url_invalid: "Invalid URL",

  address_required: "address is required",
  name_required: "name is required",
  name_invalid: "name is invalid",
  username_not_unique: "same username exists",
  images_required: "images are required",
  chain_required: "chain is required",
  chainId_required: "chainId is required",
  tokenId_required: "tokenId is required",
  owner_required: "owner is required",
  currency_required: "currency is required",
  msgsender_required: "msgsender is required",
  price_required: "price is required",
  startPrice_required: "startPrice is required",
  startTime_required: "startTime is required",
  endTime_required: "endTime is required",
  auctionId_required: "auctionId is required",
  title_required: "title is required",
  category_required: "category is required",
  description_required: "description is required",
  label_required: "label is required",
  value_required: "value is required",
  url_required: "url is required",

  user_register_success: "User is successfully registered!",
  user_register_fail: "Error occured, while registring a user!",
  user_not_exists: "User Profile is not exists",
  follow_success: "Follow successfully!",
  unfollow_success: "Unfollow successfully!",
  write_scaled_image_error: "Writing scaled stream failed",
  upload_scaled_image_s3_error: "Uploading AWS S3 stream failed",
};
